{
 "title": "Power Metrics per PDU",
 "description": "Power metrics per PDU",
 "tags": [
  "power",
  "lab",
  "rack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "targetInstance",
    "label": "pdu device",
    "query": "label_values(rPDULoadStatusLoadState, instance)"
   },
   { "name": "avgkWH_Cost", "label": "Average kWH cost", "query": ".1250" }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "gauge",
   "description": "Load as a percentage",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rPDULoadStatusLoad{instance=\"$targetInstance\"}"
    }
   ]
  },
  {
   "title": "Operating Cost",
   "type": "stat",
   "description": "average kWh over past 24h * average cost of kWh",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg_over_time(rPDUIdentDevicePowerWatts{instance=\"$targetInstance\"}[1d]) / 1000)  * ${avgkWH_Cost} * 24."
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "description": "Load measured in tenths of Amps",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "rPDULoadStatusLoad{instance=\"$targetInstance\"} * .1",
     "legendFormat": "{{instance}}, bank: {{rPDULoadStatusIndex}}"
    }
   ]
  },
  {
   "title": "Max/Min Power",
   "type": "stat",
   "description": "Power in Watts",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(rPDUIdentDevicePowerWatts{instance=\"$targetInstance\"}[24h])"
    },
    {
     "expr": "min_over_time(rPDUIdentDevicePowerWatts{instance=\"$targetInstance\"}[24h])"
    }
   ]
  },
  {
   "title": "Load State",
   "type": "graph",
   "description": "phase/bank load state",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rPDULoadStatusLoadState{instance=\"$targetInstance\"}",
     "legendFormat": "{{rPDULoadStatusLoadState}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "description": "Voltage for phase 1",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rPDUIdentDeviceLinetoLineVoltage{instance=\"$targetInstance\"}  "
    }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "graph",
   "description": "kWh over past 24h",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(rPDUIdentDevicePowerWatts{instance=\"$targetInstance\"}[1d]) / 1000)  ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "description": "Power in Watts",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "rPDUIdentDevicePowerWatts{instance=\"$targetInstance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}